credentials:
  usernames:
    drodriguez:
      email: dr507498@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: David Rodriguez
      password: abc # Will be hashed automatically
cookie:
  expiry_days: 30
  key: '1010abczyx1010' # Must be string
  name: 'hackathon'
pre-authorized:
  emails:
  - dr507498@gmail.com