cookie:
  expiry_days: 30
  key: 1010abczyx1010
  name: hackathon
credentials:
  usernames:
    dp:
      email: deeppatel0306@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Deep
      password: $2b$12$bQkeB2c9sPbAmDGiYzXjV.YAy1ZfbMYLtHvBcFP/HKfTLKbhewrJ.
    dr:
      email: drodriguez1443@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: dr
      password: $2b$12$qAunDAyHq3D0MSIHdgcFHOhQZrwszIkf09bMED2uv7rcvV9Jkg.CW
    t:
      email: t
      failed_login_attempts: 0
      logged_in: true
      name: t
      password: $2b$12$vBkz1rWVDvPsUVHmolgFB.3ryqUOL5yyrHHai4WYyGYUMsoPj5z6q
    test:
      email: test
      failed_login_attempts: 0
      logged_in: false
      name: test
      password: $2b$12$OOZsHlvqRUmJB8vyb3o7XONrVBpSDMMMrc6/.ykgz7agGIihL3TSe
pre-authorized:
  emails:
  - dr507498@gmail.com
