cookie:
  expiry_days: 30
  key: 1010abczyx1010
  name: hackathon
credentials:
  usernames:
    dr:
      email: drodriguez1443@gmail.com
      logged_in: false
      name: dr
      password: $2b$12$qAunDAyHq3D0MSIHdgcFHOhQZrwszIkf09bMED2uv7rcvV9Jkg.CW
    drodriguez:
      email: dr507498@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: David Rodriguez
      password: abc
pre-authorized:
  emails:
  - dr507498@gmail.com